/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_ld_jni_html_aidl_MyJniLib */

#ifndef _Included_com_android_ld_jni_html_aidl_MyJniLib
#define _Included_com_android_ld_jni_html_aidl_MyJniLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_ld_jni_html_aidl_MyJniLib
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_ld_jni_1html_1aidl_MyJniLib_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
